"""~30 synthetic people that populate the vector store on boot.

Enough spread that /graph returns a meaningful graph immediately (no intake
needed for the demo), with a dense ex-finance -> agent-infra cluster so the
"closest in meaning, not just topic" story has something to show.

Each dict is Profile-shaped minus `roles`, which the store derives on seed.
"""
from __future__ import annotations

PERSONAS: list[dict] = [
    # --- ex-finance -> agent infra (the demo cluster) ------------------------
    dict(id="p_maya", name="Maya Okafor", domain="agent infra",
         trajectory="quant trading -> agent infra", seeking="technical cofounder",
         tags=["agents", "evals", "quant", "python"],
         summary="Ex-quant building an eval harness for tool-using agents; wants a cofounder."),
    dict(id="p_devan", name="Devan Rao", domain="agent infra",
         trajectory="derivatives desk -> LLM orchestration", seeking="technical cofounder",
         tags=["orchestration", "llm", "routing", "infra"],
         summary="Left a derivatives desk to build a model router; seeking a cofounder."),
    dict(id="p_sung", name="Sung-min Park", domain="agent infra",
         trajectory="hedge fund -> inference infra", seeking="design partner",
         tags=["inference", "latency", "infra", "gpu"],
         summary="From a hedge fund into a low-latency inference gateway; wants design partners."),
    dict(id="p_lena", name="Lena Fischer", domain="fintech",
         trajectory="investment banking -> fintech", seeking="technical cofounder",
         tags=["fintech", "underwriting", "copilot", "credit"],
         summary="Ex-IB building an underwriting copilot for lenders; wants a technical cofounder."),
    dict(id="p_omar", name="Omar Haddad", domain="agent infra",
         trajectory="prop trading -> agent tooling", seeking="first engineer",
         tags=["observability", "agents", "tracing", "infra"],
         summary="From prop trading to agent observability; hiring a first engineer."),
    dict(id="p_marco", name="Marco Rossi", domain="agent infra",
         trajectory="backend eng -> agent infra", seeking="technical cofounder",
         tags=["agents", "workflows", "durable", "infra"],
         summary="Backend engineer building durable agent workflows; seeking a cofounder."),
    dict(id="p_ian", name="Ian Novak", domain="agent infra",
         trajectory="ML infra -> agent infra", seeking="design partner",
         tags=["agents", "memory", "infra", "vector"],
         summary="ML infra engineer building agent memory; wants design partners."),

    # --- adjacent + contrast domains ----------------------------------------
    dict(id="p_ravi", name="Ravi Menon", domain="devtools",
         trajectory="compiler eng -> devtools", seeking="design partner",
         tags=["devtools", "sdk", "compilers", "dx"],
         summary="Compiler engineer building a type-safe SDK generator; wants design partners."),
    dict(id="p_grace", name="Grace Liu", domain="bio",
         trajectory="wet lab -> computational bio", seeking="ML engineer",
         tags=["bio", "protein", "ml", "pipeline"],
         summary="Wet-lab scientist building a protein-design pipeline; looking for an ML engineer."),
    dict(id="p_tom", name="Tom Whitfield", domain="climate",
         trajectory="energy trading -> climate tech", seeking="technical cofounder",
         tags=["climate", "grid", "forecasting", "energy"],
         summary="Ex-energy trader building grid forecasting; seeking a technical cofounder."),
    dict(id="p_aisha", name="Aisha Bello", domain="consumer",
         trajectory="product design -> consumer social", seeking="growth lead",
         tags=["consumer", "social", "product", "design"],
         summary="Product designer building a small-group social app; wants a growth lead."),
    dict(id="p_niko", name="Niko Andersen", domain="robotics",
         trajectory="mechanical eng -> robotics", seeking="controls engineer",
         tags=["robotics", "hardware", "controls", "warehouse"],
         summary="Mechanical engineer building warehouse robotics; hiring controls."),
    dict(id="p_priya", name="Priya Nair", domain="security",
         trajectory="SRE -> security", seeking="design partner",
         tags=["security", "agents", "permissions", "infra"],
         summary="Ex-SRE building a permissions firewall for agents; wants design partners."),
    dict(id="p_hana", name="Hana Suzuki", domain="fintech",
         trajectory="risk analyst -> fintech", seeking="first engineer",
         tags=["fintech", "fraud", "agents", "risk"],
         summary="Risk analyst building a fraud-detection agent; hiring a first engineer."),
    dict(id="p_ben", name="Ben Carter", domain="devtools",
         trajectory="platform eng -> devtools", seeking="design partner",
         tags=["devtools", "ci", "ml", "platform"],
         summary="Platform engineer building CI for ML pipelines; looking for design partners."),
    dict(id="p_zoe", name="Zoe Martins", domain="climate",
         trajectory="data science -> climate", seeking="technical cofounder",
         tags=["climate", "carbon", "data", "accounting"],
         summary="Data scientist building a carbon-accounting engine; seeking a technical cofounder."),
    dict(id="p_sara", name="Sara Kim", domain="bio",
         trajectory="clinician -> health AI", seeking="ML engineer",
         tags=["health", "triage", "ml", "clinical"],
         summary="Clinician building a clinic triage assistant; looking for an ML engineer."),
    dict(id="p_leo", name="Leo Petit", domain="consumer",
         trajectory="growth marketing -> creator tools", seeking="technical cofounder",
         tags=["consumer", "creators", "analytics", "growth"],
         summary="Growth marketer building creator analytics; seeking a technical cofounder."),
    dict(id="p_ana", name="Ana Duarte", domain="agent infra",
         trajectory="data engineering -> agent infra", seeking="design partner",
         tags=["agents", "pipelines", "etl", "infra"],
         summary="Data engineer building data pipelines for agents; wants design partners."),
    dict(id="p_yuki", name="Yuki Tanaka", domain="fintech",
         trajectory="actuary -> insurtech", seeking="technical cofounder",
         tags=["fintech", "insurance", "pricing", "risk"],
         summary="Actuary building an insurance-pricing model; seeking a technical cofounder."),
    dict(id="p_pavel", name="Pavel Sokolov", domain="devtools",
         trajectory="kernel dev -> databases", seeking="first engineer",
         tags=["devtools", "database", "storage", "systems"],
         summary="Kernel developer building a vector database; hiring a first engineer."),
    dict(id="p_fatima", name="Fatima Zahra", domain="bio",
         trajectory="pharma -> drug discovery AI", seeking="ML engineer",
         tags=["bio", "drug-discovery", "ml", "chemistry"],
         summary="Pharma scientist building a drug-discovery model; looking for an ML engineer."),
    dict(id="p_diego", name="Diego Alvarez", domain="climate",
         trajectory="civil eng -> climate resilience", seeking="design partner",
         tags=["climate", "infrastructure", "risk", "modeling"],
         summary="Civil engineer building climate-risk models for cities; wants design partners."),
    dict(id="p_nadia", name="Nadia Petrov", domain="security",
         trajectory="pentester -> AI security", seeking="technical cofounder",
         tags=["security", "red-team", "agents", "ml"],
         summary="Pentester building red-teaming tools for AI agents; seeking a cofounder."),
    dict(id="p_kofi", name="Kofi Mensah", domain="agent infra",
         trajectory="mobile eng -> agent apps", seeking="design partner",
         tags=["agents", "mobile", "assistants", "product"],
         summary="Mobile engineer building on-device agent assistants; wants design partners."),
    dict(id="p_elena", name="Elena Ricci", domain="consumer",
         trajectory="journalist -> media tools", seeking="technical cofounder",
         tags=["consumer", "media", "editing", "content"],
         summary="Journalist building AI editing tools for newsrooms; seeking a technical cofounder."),
    dict(id="p_sam", name="Sam Whittaker", domain="fintech",
         trajectory="trader -> crypto infra", seeking="first engineer",
         tags=["fintech", "crypto", "settlement", "infra"],
         summary="Ex-trader building crypto settlement infra; hiring a first engineer."),
    dict(id="p_mei", name="Mei Chen", domain="robotics",
         trajectory="controls eng -> autonomy", seeking="perception engineer",
         tags=["robotics", "autonomy", "perception", "controls"],
         summary="Controls engineer building autonomy stacks; looking for a perception engineer."),
    dict(id="p_jonas", name="Jonas Berg", domain="devtools",
         trajectory="site reliability -> observability", seeking="design partner",
         tags=["devtools", "observability", "metrics", "infra"],
         summary="SRE building observability for ML systems; wants design partners."),
    dict(id="p_tara", name="Tara Singh", domain="agent infra",
         trajectory="research eng -> agent evals", seeking="technical cofounder",
         tags=["agents", "evals", "benchmarks", "research"],
         summary="Research engineer building agent benchmarks; seeking a technical cofounder."),
]
